### ISSUE TITLE
Return JSON

### ISSUE THREAD

**Issue by trainerbill** [GoodwayGroup/intacct-api#11]
Question since I am just beginning with these API's, but why are you parsing the response XML to JSON and not just setting the returnFormat to JSON?

**Comment by mrlannigan** [comment]
Hi @trainerbill,

Sorry for the delay in responding. The main reason for parsing xml was because the response when sending multiple control functions is not valid JSON. It's multiple JSON objects delimited concatenated together with no delimiter, not even a line break. Also, you lose some attributes about the control function's response, such as total result set count.

The JSON response format just seems like an afterthought for Intacct. Now, if we were able to get them to improve their API, I would be more than happy to work with you to convert this module to use JSON primarily.

**Comment by trainerbill** [comment]
Yeah I found that out the hard way after coverting to JSON....  Looks like they are adding node support in the near future.  FYI

https://github.com/Intacct/intacct-sdk-js

**Comment by mrlannigan** [comment]
Looks like they haven't done anything yet with the repo. I'm going to close this issue for now. If you have any ideas on possibly working around the xml to json conversion, I'm all for it. I just want to be careful about limiting the amount of information that a user has when making their requests. Hopefully, Intacct will reevaluate their API responses to _truly_ support JSON responses.
